// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alloc_cotask_mem`, `free_cotask_mem`, `get_last_error`, `str_to_utf16`, `utf16_ptr_to_str`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `fmt`, `from`

/// 1. 获取本地打印机列表（对应 C# GetPrinterList）
List<String> getPrinterList() =>
    RustLib.instance.api.crateApiPrinterModuleGetPrinterList();

/// 2. 获取默认打印机名称（对应 C# GetDeaultPrinterName）
String? getDefaultPrinter() =>
    RustLib.instance.api.crateApiPrinterModuleGetDefaultPrinter();

/// 3. 设置默认打印机（对应 C# SetPrinterToDefault）
void setDefaultPrinter({required String printerName}) => RustLib.instance.api
    .crateApiPrinterModuleSetDefaultPrinter(printerName: printerName);

/// 4. 获取打印机状态（对应 C# GetPrinterStatus）
String getPrinterStatus({required String printerName}) => RustLib.instance.api
    .crateApiPrinterModuleGetPrinterStatus(printerName: printerName);

/// 5. 添加自定义纸张（对应 C# AddCustomPaperSize）
void addCustomPaper({
  required String printerName,
  required String paperName,
  required double widthMm,
  required double heightMm,
}) => RustLib.instance.api.crateApiPrinterModuleAddCustomPaper(
  printerName: printerName,
  paperName: paperName,
  widthMm: widthMm,
  heightMm: heightMm,
);

/// 6. 删除自定义纸张（对应 C# DeleteCustomPaperSize）
void deleteCustomPaper({
  required String printerName,
  required String paperName,
}) => RustLib.instance.api.crateApiPrinterModuleDeleteCustomPaper(
  printerName: printerName,
  paperName: paperName,
);

/// 7. 发送字节到打印机（对应 C# SendBytesToPrinter）
void sendBytesToPrinter({
  required String printerName,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiPrinterModuleSendBytesToPrinter(
  printerName: printerName,
  bytes: bytes,
);

/// 8. 发送文件到打印机（对应 C# SendFileToPrinter）
void sendFileToPrinter({
  required String printerName,
  required String filePath,
}) => RustLib.instance.api.crateApiPrinterModuleSendFileToPrinter(
  printerName: printerName,
  filePath: filePath,
);

/// 9. 发送字符串到打印机（对应 C# SendStringToPrinter）
void sendStringToPrinter({required String printerName, required String s}) =>
    RustLib.instance.api.crateApiPrinterModuleSendStringToPrinter(
      printerName: printerName,
      s: s,
    );

/// 10. 检查打印机是否存在（对应 C# PrinterInList）
bool isPrinterExist({required String printerName}) => RustLib.instance.api
    .crateApiPrinterModuleIsPrinterExist(printerName: printerName);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PrinterError>>
abstract class PrinterError implements RustOpaqueInterface {}
